### ISSUE TITLE
스테이지에 그리드 밀림현상, 그리드 속에 들어간 오브젝트 이동불가

### ISSUE THREAD

**Issue by Writtic** [ENOW-IJI/console#2]
Angular에도 div 속 공간을 따로 인식해서 드래그 앤 드롭 할 수 있게 해주는 함수가 있을 것 같습니다.

**Comment by Writtic** [comment]
## angular.js drag and drop with grid

[예제 코드](http://stackoverflow.com/questions/25554672/dynamic-grid-on-drag-and-drop-bootstrap)

[예제 페이지](http://codepen.io/troepster/pen/yYeaqQ)

**Comment by ghost** [comment]
확인하고 적용해보겠습니다.
